name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: test
      run: |
        xcodebuild -target macSKKTests -scheme macSKK -resultBundlePath TestResults test
    - uses: kishikawakatsumi/xcresulttool@v1
      with:
        path: TestResults.xcresult
      if: success() || failure()
