name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-14
    steps:
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md#xcode
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_15.2.app/Contents/Developer'
    - uses: actions/checkout@v4
    - name: test
      run: |
        xcodebuild -target macSKKTests -scheme macSKK -resultBundlePath TestResults DEVELOPMENT_TEAM= test | xcpretty
    - uses: kishikawakatsumi/xcresulttool@v1
      with:
        path: TestResults.xcresult
        show-passed-tests: false
      if: success() || failure()
