name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-13
    steps:
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_15.0.app/Contents/Developer'
    - uses: actions/checkout@v3
    - name: test
      run: |
        xcodebuild -target macSKKTests -scheme macSKK -resultBundlePath TestResults DEVELOPMENT_TEAM= test
    - uses: kishikawakatsumi/xcresulttool@v1
      with:
        path: TestResults.xcresult
      if: success() || failure()
